name: Firebase Deploy

on:
  push:
    branches:
      - main

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --non-interactive


